AspNetIdentity.WebClientAdmin/Controllers/LayoutController.cs
using AspNetIdentity.WebClientAdmin.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace AspNetIdentity.WebClientAdmin.Controllers
{
    public class LayoutController : BaseController
    {
        [Authorize]
        public ActionResult SidebarRezago()
        {
            string role = GetTokenObject().role;
            GeneralConfigurations generalConfigurations = GetConfig(1);
            SidebarUserLevel sidebarUserLevel = generalConfigurations.menus.Where(w => w.role.Equals(role, System.StringComparison.OrdinalIgnoreCase)).FirstOrDefault();
            List<SidebarItem> SidebarItemList = sidebarUserLevel.links;
            
            return PartialView(SidebarItemList);
        }

        public ActionResult SidebarBarrido()
        {
            string role = GetTokenObject().role;
            GeneralConfigurations generalConfigurations = GetConfig(2);
            SidebarUserLevel sidebarUserLevel = generalConfigurations.menus.Where(w => w.role.Equals(role, System.StringComparison.OrdinalIgnoreCase)).FirstOrDefault();
            List<SidebarItem> SidebarItemList = sidebarUserLevel.links;

            return PartialView(SidebarItemList);
        }

        [Authorize]
        public ActionResult Navbar()
        {
            ViewBag.FullName = GetTokenObject().FullName;
            ViewBag.IdU = GetTokenObject().FullName;

            return PartialView();
        }
    }
}

AspNetIdentity.WebClientAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-co">
<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title - ANT FZ</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    @Styles.Render("~/Content/css")

    <link rel="shortcut icon" href="images/favicon.png" />

</head>
<body class="grey lighten-3">

    <!--Main Navigation-->
    <header>

        <!-- Navbar -->
        @{ Html.RenderAction("Navbar", "Layout"); }
        <!-- Navbar -->
        <!-- Sidebar -->
        <div id="DivRezago" style="display:none">
            @{ Html.RenderAction("SidebarRezago", "Layout"); }
        </div>
        <div id="DivBarrido" style="display:none">
            @{ Html.RenderAction("SidebarBarrido", "Layout"); }
        </div>
        
        <!-- Sidebar -->

    </header>
    <!--Main Navigation-->
    <!--Main layout-->
    <main class="pt-5 mx-lg-5">
        <div class="container-fluid mt-5">
            @*MODAL PARA DEFINIR EL MENU*@ 
            <div id="exampleModalLong" class="modal  fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class=" alert-success">
                            <div class="col-md-12 justify-content-center align-content-center text-center ">
                                <br />
                                <br />
                                <br />
                                <h1 class="">  En que quieres trabajar hoy ? </h1>
                                <br />
                                <br />
                                @*<button type="button" class="btn btn-success" data-dismiss="modal" onclick="@Url.Action("../Dashboard/Rezago", "Rezago", new { IdTable = 1 })">Rezago</button>*@
                                <a class="btn btn-success" id="BtnRezago" href='@Url.Action("../Dashboard/Rezago", "Rezago", new { IdTable = 1 })' title='Modificar'>Rezago</a>
                                <a class="btn btn-success" id="BtnBarrido" href='@Url.Action("../Dashboard/Barrido", "Barrido", new { IdTable = 2 })' title='Modificar'>Barrido</a>
                                    <input type="hidden" id="TypeSidebarHiden" name="TypeSidebarHiden" value="" />
                                <br />
                                <br />
                                <br />
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            @RenderBody()

        </div>
    </main>
    <!--Main layout-->
    <!-- SCRIPTS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {

          

            var ls;
            ls = localStorage;

            var custStr
            custStr = ls.getItem("A123");
            if (custStr == "2") {
                $('#DivRezago').show();

            } else if (custStr == "3") {
                $('#DivBarrido').show();

            }
            //window.location.href ='@Url.Action("../CaracterizacionAgronomica/index", "index")';

            $('#BtnRezago').click(function () {
                $('#DivRezago').show();
            });

            $('#BtnBarrido').click(function () {
                $('#DivBarrido').show();
            });

            $('.child').hide(); //Hide children by default

            $('.parent').children().click(function () {
                event.preventDefault();
                $(this).children('.child').slideToggle('slow');
                $(this).find('span').toggle();
            });
            console.log("ready!");

            $('.tableData').DataTable({
                dom: "B<'row'<'col-sm-6'l><'col-sm-6'f>><'row'<'col-sm-12'tr>><'row'<'col-sm-5'i><'col-sm-7'<'#colvis'>p>>",
                buttons: [
                    { "extend": 'pdf', "text": 'Pdf', "className": 'btn-outline-success' },
                    { "extend": 'excel', "text": 'Exc', "className": ' btn-outline-success ' },
                    { "extend": 'print', "text": 'Imp', "className": ' btn-outline-success ' }
                ],
                "order": [[1, "desc"]],
                "language": { "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json" },
                "pageLength": 10,
                "paging": true
            });

            $('.dataTables_length').addClass('bs-select');

            $("#MenuCloseBarrido").click(function () {
                $("#SidebarCustomBarrido").hide();
            });

            $("#MenuCloseRezago").click(function () {
                $("#SidebarCustomRezago").hide();
            });

            $(".navbar-brand").click(function () {
                if (custStr == "2") {
                    $("#SidebarCustomRezago").show(); return false;
                } else if (custStr == "3") {
                    $("#SidebarCustomBarrido").show(); return false;
                }
            });

            $('.modalUser').click(function () {

                    debugger;

                    var $buttonClicked = $(this);
                    var id = $buttonClicked.attr('data-id');
                    var options = { "backdrop": "static", keyboard: true };

                    $.ajax({
                        type: "GET",
                        url: '/Users/UserModal',
                        contentType: "application/json; charset=utf-8",
                        data: { "Id": id },
                        datatype: "json",
                        success: function (data) {
                            debugger;
                            $('#myModalContent').html(data);
                            $('#myModal').modal(options);
                            $('#myModal').modal('show');

                        },
                        error: function () {
                            alert("Dynamic content load failed.");
                        }
                    });
                });
        });
            // Animations initialization
            new WOW().init();
    </script>



</body>
</html>

AspNetIdentity.WebClientAdmin/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--===============================================================================================-->
    @Styles.Render("~/Content/cssLogin")
    <!--===============================================================================================-->
    <style type="text/css">
        #idLogin {
            background-image: url(http://sit.agenciadetierras.gov.co/web/Content/Images/bg-login-lg.jpg);
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
</head>
<body id="">
    <div>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jqueryLogin")
    @RenderSection("scripts", required: false)

</body>
</html>